#Hope?????
#name: Deploy Docker image

#on:
#  push:
#    branches:
#      - main

#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    permissions:
#      packages: write
#    steps:
#      -
#        name: Determine tags
#        id: get_tags
#        run: |
#          echo "DEV_TAG=main-latest" >> $GITHUB_ENV
#          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
#          echo "COMMIT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

#      - name: Checkout Code
#        uses: actions/checkout@v1
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GHCR_TOKEN }}
#     - name: Build and Push Docker Image
#        uses: docker/build-push-action@v2
#       with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: |
#            ghcr.io/${{ github.repository }}:${{ env.DEV_TAG }}
#            ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}