name: Build and push

on:
  push:
    branches:
      - main

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Determine tags
        id: get_tags
        run: |
          echo "DEV_TAG=main-latest" >> $GITHUB_ENV
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "COMMIT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
      -
        name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DEV_TAG }}
            ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Echo image paths
        run: |
          echo "Image path for development-latest: ghcr.io/${{ github.repository }}:${{ env.DEV_TAG }}"
          echo "Image path for commit SHA: ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}"